### ISSUE TITLE
[feature request] Single Index for Multiple Netlify Apps

### ISSUE THREAD

**Issue by codebyravi** [algolia/algoliasearch-netlify#104]
We're trying to use multiple Netlify apps to update the data in a single place. We have a usecase to display the search hits from multiple apps. So, we're trying to combine all the data from multiple apps into a single index.
It would be great if there is a feature to use a single index to crawl through multiple netlify apps. It will be great if there is an option to add more netlify apps into the inputs for a single crawler.
[plugins.inputs]
  SITE_ID = ["xxxx"]

**Comment by bodinsamuel** [comment]
Hello @codebyravi 

Thanks for your feedback, currently the crawler itself (the system managing the crawl of all websites) does not support multi-index merging so it probably won't be possible to add this options to the plugin.
However, this use case can be fixed by using multi-index search and instantsearch.js

- Frontend implementation with instantsearch.js https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/multi-index-search/js/
- algoliasearch.js function: https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/

Hope this helps ☺️

**Comment by bodinsamuel** [comment]
Closing as can not be done :)
