### ISSUE TITLE
Search bar disappears on completion of page load

### ISSUE THREAD

**Issue by bgoonz** [algolia/algoliasearch-netlify#410]
![algolia-search-bug](https://user-images.githubusercontent.com/66654881/129795642-9ced30db-05f0-47e8-8aa8-6ac5ccdb11cd.gif)
The website is 
- [website](https://bgoonz-blog.netlify.app/)
Git repo:
- [repo](https://github.com/bgoonz/BGOONZ_BLOG_2.0)

I used wget to clone the static html version of my website for which the following search bar is functional:

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@algolia/algoliasearch-netlify-frontend@1/dist/algoliasearchNetlify.css" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@algolia/algoliasearch-netlify-frontend@1/dist/algoliasearchNetlify.js"></script>
<script type="text/javascript">
  algoliasearchNetlify({
    appId: 'O6OT9G9U8Z',
    apiKey: 'b0cb3d390176e1ff4bd1ecb12fc15730',
    siteId: 'a1b7ee1a-11a7-4bd2-a341-2260656e216f',
    branch: 'master',
    selector: 'div#search',
  });
</script>
```
>...  ... ... insert html 

```html
<div id="search"></div>

```html

**Comment by bodinsamuel** [comment]
Hello,

I think the issue might be due to the fact that you have multiple `id="search` in your page and also multiple time the script to initialise the frontend `algoliasearchNetlify`. ID should be unique in a HTML page and the script can be initiliased multiple times but with different id. 

cf the source of your homepage: view-source:https://bgoonz-blog.netlify.app/
cf: https://github.com/bgoonz/BGOONZ_BLOG_2.0/search?q=algoliasearchNetlify
